name: CI
on:
  push:
    branches: [ master ]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.28
    - name: Test
      run: go test -cover -v ./...
